# Generated by Django 4.0.3 on 2022-04-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('contract_time', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('received_qty', models.CharField(blank=True, max_length=1000)),
                ('PO_qty', models.IntegerField()),
                ('unit_measure', models.CharField(max_length=2)),
                ('cost_code', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20)),
                ('ticketed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
            options={
                'ordering': ['ticketed_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(related_name='employee', to='main_app.user'),
        ),
        migrations.AddField(
            model_name='job',
            name='materials',
            field=models.ManyToManyField(related_name='material', to='main_app.material'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20)),
                ('amount', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ticket')),
            ],
            options={
                'ordering': ['invoice_date'],
            },
        ),
    ]
