# Generated by Django 4.0.3 on 2022-05-02 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('contract_time', models.IntegerField()),
                ('employees', models.ManyToManyField(related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('received_qty', models.CharField(blank=True, max_length=1000)),
                ('PO_qty', models.IntegerField()),
                ('unit_measure', models.CharField(max_length=2)),
                ('cost_code', models.CharField(max_length=25)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main_app.job')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketed_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticketed_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20)),
                ('amount', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ticket')),
            ],
            options={
                'ordering': ['invoice_date'],
            },
        ),
    ]
