# Generated by Django 4.0.3 on 2022-04-23 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('status', models.DateTimeField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'ordering': ['invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('received_qty', models.CharField(max_length=1000)),
                ('unit_measure', models.CharField(max_length=2)),
                ('PO_qty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField()),
                ('ticketed_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(max_length=500)),
                ('status', models.DateTimeField(auto_now_add=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticketed_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('contract_time', models.IntegerField()),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.invoice')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material')),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ticket')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='tickets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ticket'),
        ),
    ]
