# Generated by Django 4.0.3 on 2022-04-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('approved', 'approved'), ('missing info', 'overdue'), ('archived', 'archived')], max_length=20),
        ),
    ]
