# Generated by Django 4.0.3 on 2022-04-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_invoice_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='material_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.material'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
