# Generated by Django 4.0.3 on 2022-04-28 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='materials',
        ),
        migrations.AddField(
            model_name='material',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
            preserve_default=False,
        ),
    ]
