# Generated by Django 4.0.3 on 2022-04-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ticket_material_id_alter_ticket_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.material'),
        ),
    ]
