# Generated by Django 4.0.3 on 2022-04-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_job_materials_material_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='main_app.job'),
        ),
    ]
