# Generated by Django 4.0.3 on 2022-04-26 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_ticket_material_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tickets',
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='job',
            name='employees',
        ),
        migrations.AddField(
            model_name='job',
            name='employees',
            field=models.ManyToManyField(related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='job',
            name='materials',
        ),
        migrations.AddField(
            model_name='job',
            name='materials',
            field=models.ManyToManyField(related_name='material', to='main_app.material'),
        ),
    ]
