# Generated by Django 4.0.3 on 2022-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_job_job_id_alter_material_received_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cost_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
